parameters:
  testFramework: ''
  configuration: ''
  powerShellPlatform: ''
  TargetModule: ''

steps:
- template: get-github-pat-steps.yml
- task: PowerShell@2
  displayName: 'Check Ignored File'
  inputs:
    filePath: tools/CheckIgnoredFile.ps1
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 6.0.x'
  inputs:
    packageType: sdk
    version: 6.0.x
- task: PowerShell@2
  displayName: 'Set files changed trigger'
  inputs:
    targetType: inline
    pwsh: true
    script: |
      $subTasksFilePath = Join-Path "$(Build.SourcesDirectory)" 'artifacts' 'SubTasksFile.txt'
      Write-Host "##vso[task.setvariable variable=SubTasksFilePath]$subTasksFilePath"

      $filesChangedOutputPath = Join-Path "$(Build.SourcesDirectory)" 'artifacts' 'FilesChanged.txt'
      Write-Host "##vso[task.setvariable variable=FilesChangedOutputPath]$filesChangedOutputPath"

      $reason = "$(Build.Reason)"
      switch ($reason) {
        { $reason -in @('IndividualCI', 'BatchedCI') } {
          $trigger = "$(Build.SourceVersion)"
          $triggerType = 'Commit'
          break
        }
        'PullRequest' {
          $trigger = "$(System.PullRequest.PullRequestNumber)"
          $triggerType = 'PullRequest'
          break
        }
        { $reason -in @('Manual', 'Schedule') } {
          $targetModule = ${{ parameters.TargetModule }}
          if ('' -eq $targetModule) {
            $notModules = @('lib', 'shared')
            $src = Join-Path "$(Build.SourcesDirectory)" 'src'
            $trigger = Get-Childitem -Path $src -Directory | ForEach-Object {
              if ($_.Name -in $notModules) {
                return
              }
              return Join-Path $_.Parent.Name $_.Name
            } | Join-String -Separator ','
          } else {
            $trigger = $targetModule.Split(',') | ForEach-Object { Join-Path 'src' $_ } | Join-String -Separator ','
          }
          $triggerType = 'TargetModule'
          break
        }
        default {
          $triggerType = Null
          break
        }
      }
      Write-Host "##vso[task.setvariable variable=TriggerType]$triggerType"
      Write-Host "##vso[task.setvariable variable=Trigger]$trigger"
      Write-Host "##[section]Filter files triggered by ${reason}: ${trigger}" -ForegroundColor DarkYellow
- task: DotNetCoreCLI@2
  displayName: Filter changed files
  inputs:
    command: custom
    custom: msbuild
    arguments: 'build.proj /t:FilterBuild /p:TriggerType=$(TriggerType);Trigger=$(Trigger);FilesChangedOutputPath=$(FilesChangedOutputPath);SubTasksFilePath=$(SubTasksFilePath)'
  env:
      OCTOKITPAT: $(GithubToken)
      PowerShellPlatform: ${{ parameters.PowerShellPlatform }}
- task: PowerShell@2
  displayName: 'Set subtasks if any'
  inputs:
    targetType: inline
    pwsh: true
    script: |
      if (Test-Path $(SubTasksFilePath)) {
        Get-Content $(SubTasksFilePath) | ForEach-Object {
        if ($_ && 'Predictor' -eq $_) {
          Write-Host "##vso[task.setvariable variable=SubTaskPredictor]true"
        } elseif ($_ && 'Installer' -eq $_) {
          Write-Host "##vso[task.setvariable variable=SubTaskInstaller]true"
        } elseif ($_ && 'all' -eq $_) {
          Write-Host "##vso[task.setvariable variable=SubTaskAll]true"
        }
      }
      }
- task: PowerShell@2
  displayName: 'Analyze required files'
  inputs:
    targetType: inline
    pwsh: true
    script: |
      Write-Host "##[group]#1. Analyzing generation Id for autorest generated modules"
      $noGenerateInfo = @()
      $modules=Get-Content $(FilesChangedOutputPath) -OutVariable paths | foreach-object { if($_ -match "^src.*\.Autorest"){ Write-Output $Matches[0] } } | Select-Object -Unique
      foreach ($module in $modules) {
        $pattern = "^$module/generate-info.json"
        foreach ($path in $paths) {
          if ($path -match $pattern) {
            continue
          }
        }
        $noGenerateInfo += $module
      }
      if ($noGenerateInfo -and $noGenerateInfo.Count -gt 0) {
        $noGenerateInfo | Foreach-Object { Write-Error "No generate-info.json detected for $_" }
        exit 1
      }
      Write-Host "##[endgroup]"
- task: NodeTool@0
  displayName: Install Autorest
  inputs:
    versionSpec: '14.17.1'
    command: custom
    verbose: false
    customCommand: install autorest@latest
- task: PowerShell@2
  displayName: Setup environment for Autorest
  inputs:
    targetType: inline
    script: "$env:NODE_OPTIONS=\"--max-old-space-size=65536\""
    pwsh: true
- task: PowerShell@2
  displayName: 'Check Ignored File'
  inputs:
    filePath: tools/CheckIgnoredFile.ps1
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 6.0.x'
  inputs:
    packageType: sdk
    version: 6.0.x
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: custom
    custom: msbuild
    arguments: 'build.proj /t:Build /p:Configuration=${{ parameters.configuration }};TestFramework=${{ parameters.testFramework }}'
  env:
      OCTOKITPAT: $(GithubToken)
      PowerShellPlatform: ${{ parameters.powerShellPlatform }}
- task: PowerShell@2
  displayName: 'Write pipeline result'
  inputs:
    targetType: inline
    pwsh: true
    script: |
      $pipelineScript = Join-Path "$(Build.SourcesDirectory)" 'tools' 'ExecuteCIStep.ps1'
      $repoArtifact = Join-Path "$(Build.SourcesDirectory)" 'artifacts'
      . $pipelineScript -Build -TriggerType "$(Build.Reason)" -Trigger $(Trigger) -RepoArtifacts $repoArtifact -Configuration ${{ parameters.configuration }}
- task: DotNetCoreCLI@2
  displayName: 'SubTask Predictor'
  condition: or(eq(variables.SubTaskPredictor, true), eq(variables.SubTaskAll, true))
  inputs:
    command: custom
    custom: msbuild
    arguments: 'build.proj /t:AzToolsPredictor'
- task: DotNetCoreCLI@2
  displayName: 'SubTask Installer'
  condition: or(eq(variables.SubTaskInstaller, true), eq(variables.SubTaskAll, true))
  inputs:
    command: custom
    custom: msbuild
    arguments: 'build.proj /t:AzToolsInstaller'
- template: publish-artifacts-steps.yml
  parameters:
    artifactName: build-${{ parameters.testFramework }}