parameters:
  TargetModule: ''

steps:
- template: get-github-pat-steps.yml
- task: Bash@3
  displayName: 'Print pipeline environment variables'
  inputs:
    targetType: inline
    script: |
      printenv
- task: PowerShell@2
  displayName: 'Check Ignored File'
  inputs:
    filePath: tools/CheckIgnoredFile.ps1
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 6.0.x'
  inputs:
    packageType: sdk
    version: 6.0.x
- task: PowerShell@2
  displayName: 'Set files changed trigger'
  inputs:
    targetType: inline
    script: |
      $reason = "$(Build.Reason)"
      switch ($reason) {
        { $reason -in @('IndividualCI', 'BatchedCI') } {
          $trigger = "$(Build.SourceVersion)"
          $triggerType = 'Commit'
          break
        }
        'PullRequest' {
          $trigger = "$(System.PullRequest.PullRequestNumber)"
          $triggerType = 'PullRequest'
          break
        }
        { $reason -in @('Manual', 'Schedule') } {
          $targetModule = ${{ parameters.TargetModule }}
          if ('' -eq $targetModule) {
            $notModules = @('lib', 'shared')
            $src = Join-Path "$(Build.SourcesDirectory)" 'src'
            $trigger = Get-Childitem -Path $src -Directory | ForEach-Object {
              if ($_.Name -in $notModules) {
                return
              }
              return Join-Path $_.Parent.Name $_.Name
            } | Join-String -Separator ','
          } else {
            $trigger = $targetModule.Split(',') | ForEach-Object { Join-Path 'src' $_ } | Join-String -Separator ','
          }
          $triggerType = 'TargetModule'
          break
        }
        default {
          $triggerType = Null
          break
        }
      }
      Write-Host "##vso[task.setvariable variable=triggerType]$TriggerType"
      Write-Host "##vso[task.setvariable variable=trigger]$Trigger"
      Write-Host "Filter files triggered by ${reason}: ${trigger}" -ForegroundColor DarkYellow

      $subTasksFilePath = Join-Path $"(Build.SourcesDirectory)" 'artifacts' 'SubTasksFile.txt'
      Write-Host "##vso[task.setvariable variable=subTasksFilePath]$SubTasksFilePath"
- task: DotNetCoreCLI@2
  displayName: Filter when commit or pull request
  inputs:
    command: custom
    custom: msbuild
    arguments: 'build.proj /t:FilterBuild /p:TriggerType=${{ variables.TriggerType }};Trigger=${{ variables.Trigger }};SubTasksFilePath=${{ variables.SubTasksFilePath }}'
  env:
      OCTOKITPAT: $(GithubToken)
      PowerShellPlatform: ${{ parameters.PowerShellPlatform }}
- task: PowerShell@2
  displayName: 'Set subtasks if any'
  inputs:
    targetType: inline
    script: |
      Get-Content | ${{ variables.SubTasksFilePath }} | ForEach-Object {
        if ($_ && 'Predictor' -eq $_) {
          Write-Host "##vso[task.setvariable variable=SubTaskPredictor]true"
        } elseif ($_ && 'Installer' -eq $_) {
          Write-Host "##vso[task.setvariable variable=SubTaskInstaller]true"
        } elseif ($_ && 'all' -eq $_) {
          Write-Host "##vso[task.setvariable variable=SubTaskAll]true"
        }
      }