resources:
- repo: self
  fetchDepth: 1

pool:
  vmImage: 'Ubuntu-16.04'
#Your build pipeline references the ‘Configuration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971

steps:
- powershell: 'Install-Module platyPS -Force -Confirm:$false -Scope CurrentUser'
  displayName: 'Install platyPS'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: custom
    custom: msbuild
    arguments: 'build.proj /t:Build /p:Configuration=$(Configuration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: custom
    custom: msbuild
    arguments: 'build.proj /t:Test /p:Configuration=$(Configuration)'

- task: PublishPipelineArtifact@0
  displayName: 'Save artifacts'
  inputs:
    artifactName: artifacts
    targetPath: artifacts

