variables:
  Windows: windows
  WindowsVm: VS2017-Win2016
  TestFramework: net472
  TestTarget: TestNet472

jobs:
- job: Build
  displayName: Build
  condition: succeeded()
  pool:
    vmImage: ${{ variables['WindowsVm'] }}

  steps:
  - template: util/build-steps.yml
    parameters:
      osName: ${{ variables['Windows'] }}
      vmImage: ${{ variables['WindowsVm'] }}
      testFramework: ${{ variables['TestFramework'] }}

- job: Test
  displayName: Test
  dependsOn: Build
  condition: succeeded()
  timeoutInMinutes: 120
  pool:
    vmImage: ${{ variables['WindowsVm'] }}

  steps:
  - template: util/test-steps.yml
    parameters:
      osName: ${{ variables['Windows'] }}
      vmImage: ${{ variables['WindowsVm'] }}
      testFramework: ${{ variables['TestFramework'] }}
      testTarget: ${{ variables['TestTarget'] }}