variables:
  windows: windows
  windowsVm: VS2017-Win2016
  linux: linux
  linuxVm: Ubuntu-16.04
  macOS: macOS
  macOSVm: macOS-10.13
  testFramework: netcoreapp2.1
  testTarget: Test

jobs:
- job: Build
  displayName: Build
  condition: succeeded()
  strategy:
    matrix:
      ${{ variables['windows'] }}:
        osName: ${{ variables['windows'] }}
        vmImage: ${{ variables['windowsVm'] }}
      ${{ variables['linux'] }}:
        osName: ${{ variables['linux'] }}
        vmImage: ${{ variables['linuxVm'] }}
      ${{ variables['macOS'] }}:
        osName: ${{ variables['macOS'] }}
        vmImage: ${{ variables['macOSVm'] }}
  pool:
    vmImage: ${{ variables['vmImage'] }}

  steps:
  - template: util/build-steps.yml
    parameters:
      osName: ${{ variables['osName'] }}
      vmImage: ${{ variables['vmImage'] }}
      testFramework: ${{ variables['testFramework'] }}

- job: Analyze
  displayName: Analyze
  dependsOn: Build
  condition: succeeded()
  strategy:
    matrix:
      ${{ variables['windows'] }}:
        osName: ${{ variables['windows'] }}
        vmImage: ${{ variables['windowsVm'] }}
      ${{ variables['linux'] }}:
        osName: ${{ variables['linux'] }}
        vmImage: ${{ variables['linuxVm'] }}
      ${{ variables['macOS'] }}:
        osName: ${{ variables['macOS'] }}
        vmImage: ${{ variables['macOSVm'] }}
  pool:
    vmImage: ${{ variables['vmImage'] }}

  steps:
  - template: util/analyze-steps.yml
    parameters:
      osName: ${{ variables['osName'] }}
      vmImage: ${{ variables['vmImage'] }}

- job: Test
  displayName: Test
  dependsOn: Build
  condition: succeeded()
  timeoutInMinutes: 120
  strategy:
    matrix:
      ${{ variables['windows'] }}:
        osName: ${{ variables['windows'] }}
        vmImage: ${{ variables['windowsVm'] }}
      ${{ variables['linux'] }}:
        osName: ${{ variables['linux'] }}
        vmImage: ${{ variables['linuxVm'] }}
      ${{ variables['macOS'] }}:
        osName: ${{ variables['macOS'] }}
        vmImage: ${{ variables['macOSVm'] }}
  pool:
    vmImage: ${{ variables['vmImage'] }}

  steps:
  - template: util/test-steps.yml
    parameters:
      osName: ${{ variables['osName'] }}
      vmImage: ${{ variables['vmImage'] }}
      testFramework: ${{ variables['testFramework'] }}
      testTarget: ${{ variables['testTarget'] }}