variables:
  Windows: windows
  WindowsVm: VS2017-Win2016
  Linux: linux
  LinuxVm: Ubuntu-16.04
  MacOS: macOS
  MacOSVm: macOS-10.13
  TestFramework: netcoreapp2.1
  TestTarget: Test
  Configuration: Debug

jobs:
- job: Build
  displayName: Build
  condition: succeeded()
  strategy:
    matrix:
      ${{ variables['Windows'] }}:
        osName: ${{ variables['Windows'] }}
        vmImage: ${{ variables['WindowsVm'] }}
      ${{ variables['Linux'] }}:
        osName: ${{ variables['Linux'] }}
        vmImage: ${{ variables['LinuxVm'] }}
      ${{ variables['MacOS'] }}:
        osName: ${{ variables['MacOS'] }}
        vmImage: ${{ variables['MacOSVm'] }}
  pool:
    vmImage: $(vmImage)

  steps:
  - template: util/build-steps.yml
    parameters:
      osName: $(osName)
      vmImage: ${{ variables.vmImage }}
      testFramework: ${{ variables['TestFramework'] }}
      configuration: ${{ variables['Configuration'] }}

- job: Analyze
  displayName: Analyze
  dependsOn: Build
  condition: succeeded()
  strategy:
    matrix:
      ${{ variables['Windows'] }}:
        osName: ${{ variables['Windows'] }}
        vmImage: ${{ variables['WindowsVm'] }}
      ${{ variables['Linux'] }}:
        osName: ${{ variables['Linux'] }}
        vmImage: ${{ variables['LinuxVm'] }}
      ${{ variables['MacOS'] }}:
        osName: ${{ variables['MacOS'] }}
        vmImage: ${{ variables['MacOSVm'] }}
  pool:
    vmImage: $(vmImage)

  steps:
  - template: util/analyze-steps.yml
    parameters:
      osName: $(osName)
      vmImage: ${{ variables.vmImage }}
      configuration: ${{ variables['Configuration'] }}

- job: Test
  displayName: Test
  dependsOn: Build
  condition: succeeded()
  timeoutInMinutes: 120
  strategy:
    matrix:
      ${{ variables['Windows'] }}:
        osName: ${{ variables['Windows'] }}
        vmImage: ${{ variables['WindowsVm'] }}
      ${{ variables['Linux'] }}:
        osName: ${{ variables['Linux'] }}
        vmImage: ${{ variables['LinuxVm'] }}
      ${{ variables['MacOS'] }}:
        osName: ${{ variables['MacOS'] }}
        vmImage: ${{ variables['MacOSVm'] }}
  pool:
    vmImage: $(vmImage)

  steps:
  - template: util/test-steps.yml
    parameters:
      osName: $(osName)
      vmImage: ${{ variables.vmImage }}
      testFramework: ${{ variables['TestFramework'] }}
      testTarget: ${{ variables['TestTarget'] }}
      configuration: ${{ variables['Configuration'] }}