variables:
  WindowsName: windows
  WindowsImage: VS2017-Win2016
  TestFramework: netcoreapp2.1
  Configuration: Release

jobs:
- job: Build
  displayName: Build
  condition: succeeded()
  pool:
    vmImage: ${{ variables.WindowsImage }}

  steps:
  - template: util/build-steps.yml
    parameters:
      osName: ${{ variables.WindowsName }}
      testFramework: ${{ variables.TestFramework }}
      configuration: ${{ variables.Configuration }}