variables:
  WindowsName: windows
  WindowsImage: VS2017-Win2016
  Configuration: Release
  CodeSign: true

jobs:
- job: Build
  displayName: Build
  condition: succeeded()
  pool:
    vmImage: ${{ variables.WindowsImage }}

  steps:
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: custom
      custom: msbuild
      arguments: 'build.proj /t:Build;GenerateHelp;Publish /p:Configuration=${{ variables.Configuration }};CodeSign=${{ variables.CodeSign }}'
  - template: publish-artifacts-steps.yml
    parameters:
      artifactName: build-${{ variables.WindowsName }}