parameters:
- name: win_ps
  displayName: Windows PowerShell Version
  type: string
  default: 5.1.14
- name: ps7_2
  displayName: PowerShell 7.2.x Version
  type: string
  default: 7.2.8
- name: ps7_3
  displayName: PowerShell 7.3.x Version
  type: string
  default: 7.3.*
- name: ps7_4
  displayName: PowerShell 7.4.x Version
  type: string
  default: 7.4.*
- name: latest_ps
  displayName: PowerShell Latest Version
  type: string
  default: latest
- name: preview_ps
  displayName: PowerShell Preview Version
  type: string
  default: preview
- name: netCoreVersion
  displayName: .NET Version
  type: string
  default: 6.0.x
- name: netCoreVersion_7
  displayName: .NET Version 7
  type: string
  default: 7.0.x
- name: netCoreVersion_8
  displayName: .NET Version 8
  type: string
  default: 8.0.x

variables:
  winAgentPoolName: pool-windows-2019
  winAgentPoolVMImage: ''
  linuxAgentPoolName: pool-ubuntu-2004
  linuxAgentPoolVMImage: ''
  macOsAgentPoolName: Azure Pipelines
  macOsAgentPoolVMImage: macOS-12

pr: none
trigger: none

jobs:
- template: util/smoke-test-steps.yml
  parameters:
    name: 'Linux_PS7_4_X_SmokeTest'
    agentPoolName: ${{ variables.linuxAgentPoolName }}
    agentPoolVMImage: ${{ variables.linuxAgentPoolVMImage }}
    psVersion: ${{ parameters.ps7_4 }}
    netCoreVersion: ${{ parameters.netCoreVersion_8 }}

- template: util/smoke-test-steps.yml
  parameters:
    name: 'MacOS_PS7_4_X_SmokeTest'
    agentPoolName: ${{ variables.macOsAgentPoolName }}
    agentPoolVMImage: ${{ variables.macOsAgentPoolVMImage }}
    psVersion: ${{ parameters.ps7_4 }}
    netCoreVersion: ${{ parameters.netCoreVersion_8 }}
